---
# defaults file for containers
  servers: 3
  mysql_image_version: 8.0.43

# cnf template
  mysql_server_id: 1
  mysql_expire_logs_days: "1"
  mysql_binlog_format: "ROW"
  mysql_max_binlog_size: "10M"

